name: gantz
on: [push, pull_request]
jobs:
  rustfmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt
    - name: Run rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  cargo-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --verbose

  cargo-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose

  cargo-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: cargo doc
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --verbose

  cargo-publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    env:
      CRATESIO_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Cargo publish gantz_derive
      continue-on-error: true
      run: cargo publish --token $CRATESIO_TOKEN --manifest-path gantz_derive/Cargo.toml
    - name: Cargo publish gantz_core
      continue-on-error: true
      run: cargo publish --token $CRATESIO_TOKEN --manifest-path gantz_core/Cargo.toml
    - name: Cargo publish gantz
      continue-on-error: true
      run: cargo publish --token $CRATESIO_TOKEN --manifest-path gantz/Cargo.toml
